[tool.poetry]
name = "interpret_fair"
version = "0.1.0"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
shap = "^0.42.0"
matplotlib = "^3.8.0"
pandas = "^2.1.1"
scikit-learn = "^1.3.0"
numpy = "^1.25.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
